PyTorch is an open-source deep learning framework developed by Facebook (Meta).

PyTorch is a popular open-source deep learning framework known for its flexibility, dynamic computation graphs, and ease of use, making it a favorite for research and development.
Popular in research, academic settings, and prototyping due to intuitive syntax and debugging ease.

Tensors in PyTorch are similar to NumPy arrays but support GPU acceleration.

Use PyTorch if you want flexibility, ease of debugging, and research-oriented training.

Use TensorFlow if you prefer built-in training routines and large-scale production deployment



Unlike TensorFlow, PyTorch tensors are mutable, meaning they can be modified in place

In [ ]:
import tensorflow as tf

# Create a TensorFlow tensor
x = tf.constant([1, 2, 3])

# Attempting to modify the tensor (This will cause an error!)
# x[0] = 10  #  TensorFlow tensors are immutable

# Instead, you must create a new tensor
x_new = x + 5  # Adds 5 to all elements, but creates a new tensor

print(x_new)  # Output: tf.Tensor([6 7 8], shape=(3,), dtype=int32)




import torch

# Create a PyTorch tensor
x = torch.tensor([1, 2, 3])

# Modify the tensor in-place
x[0] = 10  # Changing the first element
x += 5     # Adding 5 to all elements

print(x)  # Output: tensor([15, 7, 8])

tf.Tensor([6 7 8], shape=(3,), dtype=int32)
tensor([15,  7,  8])


Both PyTorch and TensorFlow support automatic differentiation, but PyTorch makes it easier and more intuitive using autograd.

In [ ]:
import tensorflow as tf

# Create a TensorFlow variable
x = tf.Variable(2.0)

with tf.GradientTape() as tape:                    #use tf.GradientTape() to record operations
    y = x ** 3  # Define function y = x^3

# Compute gradient dy/dx
grad = tape.gradient(y, x)

# Print gradient (dy/dx = 3x^2 at x=2)
print(grad.numpy())  # Output: 12.0


import torch

# Create a tensor with requires_grad=True to track gradients
x = torch.tensor(2.0, requires_grad=True)

# Define function y = x^3
y = x ** 3

# Compute gradient dy/dx
y.backward()

# Print gradient (dy/dx = 3x^2 at x=2)
print(x.grad)  # Output: tensor(12.)


12.0
tensor(12.)


 Working with GPU in PyTorch vs. TensorFlow


TensorFlow: Automatically assigns operations to available GPUs.

PyTorch: Requires explicit tensor and model assignment to a GPU.

In [ ]:
import tensorflow as tf

# Check available GPUs
print("Available GPUs:", tf.config.list_physical_devices('GPU'))

# Create tensors (automatically assigned to GPU if available)
x = tf.constant([1.0, 2.0, 3.0])
y = tf.constant([4.0, 5.0, 6.0])

# Perform computation
z = x + y
print(z)  # Output: tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)



import torch

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Create a tensor and move it to GPU
x = torch.tensor([1.0, 2.0, 3.0]).to(device)
y = torch.tensor([4.0, 5.0, 6.0]).to(device)

# Perform computation on GPU
z = x + y
print(z)  # Output: tensor([5., 7., 9.], device='cuda:0')



Available GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Using device: cuda
tensor([5., 7., 9.], device='cuda:0')


In [ ]:
import torch

**AutoGrad Function**

In [ ]:
# The autograd package provides automatic differentiation
# for all operations on Tensors

# requires_grad = True -> tracks all operations on the tensor.
x = torch.tensor([ 1.0156, -0.3449,  0.1732], requires_grad=True)

y = x + 2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)
y.backward(torch.ones_like(y))
print(x.grad)
# Do more operations on y
z = y * y
print(z)
z = z.mean()
print(z)

# Let's compute the gradients with backpropagation
# When we finish our computation we can call .backward() and have all the gradients computed automatically.
# The gradient for this tensor will be accumulated into .grad attribute.
# It is the partial derivate of the function w.r.t. the tensor
z.backward(torch.ones_like(z))
print(x.grad) # dz/dx



tensor([ 1.0156, -0.3449,  0.1732], requires_grad=True)
tensor([3.0156, 1.6551, 2.1732], grad_fn=<AddBackward0>)
tensor([1., 1., 1.])
tensor([9.0938, 2.7394, 4.7228], grad_fn=<MulBackward0>)
tensor(5.5187, grad_fn=<MeanBackward0>)
tensor([3.0104, 2.1034, 2.4488])


**Stop a tensor from tracking history**

In [ ]:
# For example during our training loop when we want to update our weights
# then this update operation should not be part of the gradient computation
# - x.requires_grad_(False)
# - x.detach()
# - wrap in 'with torch.no_grad():

In [ ]:
# .requires_grad_(...) changes an existing flag in-place.
a = torch.randn(2, )
print(a)
print(a.requires_grad)
b = ((a * 3) / (a - 1))[]
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.requires_grad)
print(b)


tensor([ 1.8471, -0.5652])
False
None
True
True
tensor(3.7314, grad_fn=<SumBackward0>)


In [ ]:
# .detach(): get a new Tensor with the same content but no gradient computation:
a = torch.tensor([1.0,2.0], requires_grad=True)
print(a.requires_grad)
# b = a.detach()
d=a*a
print(d)
# d=d.mean()
d.backward(torch.ones_like(d))
print(a.grad)
# c=torch.tensor([1,2],)
# print(b.requires_grad)


True
tensor([1., 4.], grad_fn=<MulBackward0>)
tensor([2., 4.])


In [ ]:
# wrap in 'with torch.no_grad():'
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((a ** 2).requires_grad)

True
False


**Emptying Gradients**

In [ ]:
# backward() accumulates the gradient for this tensor into .grad attribute.
# !!! We need to be careful during optimization !!!
# Use .zero_() to empty the gradients before a new optimization step!
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # just a dummy example
    model_output = (weights*3).sum()
    model_output.backward()

    print(weights.grad)

    # optimize model, i.e. adjust weights...
    with torch.no_grad():
        weights -= 0.1 * weights.grad

    # this is important! It affects the final weights & output
    weights.grad.zero_()

print(weights)
print(model_output)

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)


**Backpropagation for Linear Regression Example**

In [ ]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

# This is the parameter we want to optimize -> requires_grad=True
w = torch.tensor(1.0, requires_grad=True)
print(w)
# forward pass to compute loss
y_predicted = w * x
loss = (y_predicted - y)**2
print(loss)

# backward pass to compute gradient dLoss/dw
loss.backward()
print(w.grad)

# update weights
# next forward and backward pass...

# continue optimizing:
# update weights, this operation should not be part of the computational graph
with torch.no_grad():
    w -= 0.01 * w.grad
# don't forget to zero the gradients
w.grad.zero_()

# next forward and backward pass...

tensor(1., requires_grad=True)
tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


tensor(0.)

**Gradient Descent for Linear Regression (Manually)**



In [ ]:
import numpy as np

# Compute every step manually

# Linear regression
# f = w * x

# here : f = 2 * x
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

# J = MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N * 2x(w*x - y)
def gradient(x, y, y_pred):
    return np.mean(2*x*(y_pred - y))

print(f'Prediction before training: f(5) = {forward(5):.3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # calculate gradients
    dw = gradient(X, Y, y_pred)

    # update weights
    w =w- learning_rate * dw

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Prediction after training: f(5) = {forward(5):.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506905
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000


**Gradient Descent (Automatic)**

In [ ]:
import torch

# Here we replace the manually computed gradient with autograd

# Linear regression
# f = w * x

# here : f = 2 * x
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

print(f'Prediction before training: f(5) = {forward(5).item():.3f}')

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # calculate gradients = backward pass
    l.backward()
    dw=w.grad

    # update weights
    #w.data = w.data - learning_rate * w.grad
    with torch.no_grad():
        w -= learning_rate * dw

    # zero the gradients after updating
    w.grad.zero_()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.8f}')

print(f'Prediction after training: f(5) = {forward(5).item():.3f}')

Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Prediction after training: f(5) = 10.000
